server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-registry:80/eureka/

spring:
  cloud:
    gateway:
      routes:
          - id: msempleados
            uri: lb://msempleados
            predicates:
              - Path=/api/v1/empleados/**
          - id: msdepartamentos
            uri: lb://msdepartamentos
            predicates:
              - Path=/api/v1/departamentos/**