server:
  port: 80
  servlet:
    context-path: /config-server

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-registry:80/eureka/