services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8060:80"
    networks:
      tucan-net:
        aliases:
          - api-gateway
    deploy:
      resources:
        limits:
          memory: 400M

networks:
  tucan-net:
    external: true