# Etapa 1: Construcción (Build) con Java 21
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app

# Copiamos el pom y descargamos dependencias
COPY pom.xml .
RUN mvn dependency:go-offline

# Copiamos el código fuente y empaquetamos
COPY src ./src
RUN mvn clean package -DskipTests

# Etapa 2: Ejecución (Runtime) con Java 21
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app

# Creamos la carpeta para las configuraciones (Config Server)
RUN mkdir /app/config-repo

# Copiamos el JAR generado
COPY --from=build /app/target/*.jar app.jar

EXPOSE 80
ENTRYPOINT ["java", "-jar", "app.jar"]