services:
  service-registry:
    build: .
    container_name: service-registry
    ports:
      - "8761:80"
    networks:
      tucan-net:
        aliases:
          - service-registry 
    deploy:
      resources:
        limits:
          memory: 400M

networks:
  tucan-net:
    external: true