services:
  service-registry:
    build: .
    container_name: service-registry
    ports:
      - "8761:80"
    networks:
      tucan-net:
        aliases:
          - service-registry 

networks:
  tucan-net:
    external: true