services:
  servicio-prueba:
    build: .
    container_name: servicio-prueba
    ports:
      - "8854:80"
    networks:
      tucan-net:
        aliases:
          - servicio-prueba

networks:
  tucan-net:
    external: true