services:
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    container_name: test-back
    #ports: 
    #  - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/target
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    networks:
      tucan-externo:
        aliases:
          - backtest
  
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: test-front
    ports: 
    - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro #permisos de solo lectura para nginx en la raíz del código html
      - ./frontend/nginx.test.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back
    networks:
      - tucan-externo

networks:
  tucan-externo:
    driver: bridge