services:
  msempleados:
    build: .
    container_name: msempleados
    expose:
      - "80"
    networks:
      tucan-net:
        aliases:
          - msempleados
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  tucan-net:
    external: true